//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogulReport.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MogulReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Axis 的本地化字符串。
        /// </summary>
        internal static string DataTableAxis {
            get {
                return ResourceManager.GetString("DataTableAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drilling 的本地化字符串。
        /// </summary>
        internal static string DataTableCircle {
            get {
                return ResourceManager.GetString("DataTableCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coaxial 的本地化字符串。
        /// </summary>
        internal static string DataTableCoaxial {
            get {
                return ResourceManager.GetString("DataTableCoaxial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluation 的本地化字符串。
        /// </summary>
        internal static string DatatableEvaluation {
            get {
                return ResourceManager.GetString("DatatableEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset.X 的本地化字符串。
        /// </summary>
        internal static string DataTableExcentX {
            get {
                return ResourceManager.GetString("DataTableExcentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset.Y 的本地化字符串。
        /// </summary>
        internal static string DataTableExcentY {
            get {
                return ResourceManager.GetString("DataTableExcentY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string DataTableFilter {
            get {
                return ResourceManager.GetString("DataTableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MULTI POLAR RADIAL
        ///Name :   的本地化字符串。
        /// </summary>
        internal static string DataTableHeader1 {
            get {
                return ResourceManager.GetString("DataTableHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datum 的本地化字符串。
        /// </summary>
        internal static string DataTableHeader2 {
            get {
                return ResourceManager.GetString("DataTableHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string DataTableHeader3 {
            get {
                return ResourceManager.GetString("DataTableHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesuring Point 的本地化字符串。
        /// </summary>
        internal static string DataTableMessPt {
            get {
                return ResourceManager.GetString("DataTableMessPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posiz.Z 的本地化字符串。
        /// </summary>
        internal static string DataTablePosZ {
            get {
                return ResourceManager.GetString("DataTablePosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string DataTableRef {
            get {
                return ResourceManager.GetString("DataTableRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roundness 的本地化字符串。
        /// </summary>
        internal static string DataTableRoundness {
            get {
                return ResourceManager.GetString("DataTableRoundness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 d 的本地化字符串。
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product-Nr. : __________________     ___________                
        ///Page : _______   to : _______ 的本地化字符串。
        /// </summary>
        internal static string HeaderString1 {
            get {
                return ResourceManager.GetString("HeaderString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 μm 的本地化字符串。
        /// </summary>
        internal static string micrometer {
            get {
                return ResourceManager.GetString("micrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 m 的本地化字符串。
        /// </summary>
        internal static string middle {
            get {
                return ResourceManager.GetString("middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mm 的本地化字符串。
        /// </summary>
        internal static string millimeter {
            get {
                return ResourceManager.GetString("millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 u 的本地化字符串。
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
    }
}
