//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogulReport.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MogulReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Axis 的本地化字符串。
        /// </summary>
        internal static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coaxial 的本地化字符串。
        /// </summary>
        internal static string Coaxial {
            get {
                return ResourceManager.GetString("Coaxial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datum 的本地化字符串。
        /// </summary>
        internal static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ° 的本地化字符串。
        /// </summary>
        internal static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 u 的本地化字符串。
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drilling 的本地化字符串。
        /// </summary>
        internal static string Drilling {
            get {
                return ResourceManager.GetString("Drilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluation 的本地化字符串。
        /// </summary>
        internal static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset.X 的本地化字符串。
        /// </summary>
        internal static string ExcentX {
            get {
                return ResourceManager.GetString("ExcentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset.Y 的本地化字符串。
        /// </summary>
        internal static string ExcentY {
            get {
                return ResourceManager.GetString("ExcentY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product-Nr. 的本地化字符串。
        /// </summary>
        internal static string HeaderString1 {
            get {
                return ResourceManager.GetString("HeaderString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear 的本地化字符串。
        /// </summary>
        internal static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Measuring Point 的本地化字符串。
        /// </summary>
        internal static string MeasuringPoint {
            get {
                return ResourceManager.GetString("MeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 μm 的本地化字符串。
        /// </summary>
        internal static string micrometer {
            get {
                return ResourceManager.GetString("micrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 m 的本地化字符串。
        /// </summary>
        internal static string middle {
            get {
                return ResourceManager.GetString("middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mm 的本地化字符串。
        /// </summary>
        internal static string millimeter {
            get {
                return ResourceManager.GetString("millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MULTI POLAR RADIAL 的本地化字符串。
        /// </summary>
        internal static string MultiCircleHeader {
            get {
                return ResourceManager.GetString("MultiCircleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MULTI LINEAR Z 的本地化字符串。
        /// </summary>
        internal static string MultiLineHeader {
            get {
                return ResourceManager.GetString("MultiLineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel 的本地化字符串。
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posit. C 的本地化字符串。
        /// </summary>
        internal static string PosC {
            get {
                return ResourceManager.GetString("PosC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posiz.Y 的本地化字符串。
        /// </summary>
        internal static string PosZ {
            get {
                return ResourceManager.GetString("PosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roundness 的本地化字符串。
        /// </summary>
        internal static string Roundness {
            get {
                return ResourceManager.GetString("Roundness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slope 的本地化字符串。
        /// </summary>
        internal static string Slope {
            get {
                return ResourceManager.GetString("Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Straightness 的本地化字符串。
        /// </summary>
        internal static string Straightness {
            get {
                return ResourceManager.GetString("Straightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 o 的本地化字符串。
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
    }
}
